version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      POSTGRES_DB: stats
    ports:
      - 5432:5432
  app:
    image: stats-service
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./main.Dockerfile
  migrations:
    image: migrations
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - app
    build:
      context: .
      dockerfile: ./migrations.Dockerfile
